name: Build (MSVC)

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      target_ref:
        description: 'commit hash'
        required: false
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_ref || github.ref }}

      - name: Get commit hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: C:\vcpkg-cache
          key: vcpkg-msvc-${{ hashFiles('vcpkg.json') }}

      - name: Configure CMake
        run: |
          cmake -S . -B build/ `
            -DCMAKE_BUILD_TYPE=Release `
            -DVCPKG_TARGET_TRIPLET=x64-windows-static `
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
        env:
          VCPKG_BINARY_SOURCES: "clear;files,C:/vcpkg-cache,readwrite"

      - name: Build with CMake
        run: |
          cmake --build build/ --config Release

      - name: Prepare artifact
        run: |
          mkdir artifact
          copy build\Release\2dx-gsm.dll artifact\
          copy dist\2dx-gsm.ini artifact\

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 2dx-gsm-${{ steps.vars.outputs.commit_hash }}-msvc
          path: artifact/
